apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- if .Values.reloader.enabled }}
  annotations:
    configmap.reloader.stakater.com/reload: {{ include "app.fullname" . }}
  {{- end }}
spec:
  revisionHistoryLimit: 2
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.imagePullSecrets.enable }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          envFrom:
          {{- if .Values.environment }}
            - configMapRef:
                name: {{ include "app.fullname" . }}
          {{- end }}
          
          {{- with .Values.startupProbe }}
            {{- if and (hasKey . "enabled") .enabled }}
          startupProbe:
            {{- unset . "enabled" | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}
          
          {{- with .Values.livenessProbe }}
            {{- if and (hasKey . "enabled") .enabled }}
          livenessProbe:
            {{- unset . "enabled" | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}

          {{- with .Values.readinessProbe }}
            {{- if and (hasKey . "enabled") .enabled }}
          readinessProbe:
            {{- unset . "enabled" | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}
          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
