nameOverride: ""
fullnameOverride: ""

image:
  repository: redis
  tag: "7.4.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8081

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

autoscaling:
  enabled: false

volumes: []

volumeMounts: []

tolerations: []

affinity: {}

reloader:
  enabled: false

startupProbe:
  enabled: false
  
readinessProbe:
  enabled: false

imagePullSecrets: 
  enable: false
 
livenessProbe:
  enabled: false
  
ingress:
  enabled: false
  classname: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

nodeSelector: {}

resources:
  limits:
    cpu: 4 
    memory: 8Gi
  requests:
    cpu: 1
    memory: 2Gi