image:
  tag: "7.4.1"
replicaCount: 1
auth:
  enabled: false
resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
config:
  maxmemory: "512mb"
  maxmemory-policy: "allkeys-lru"
