replicaCount: 1
auth:
  enabled: true
  # Prefer using an existing Secret in prod:
  # existingSecret: "redis-auth"
  # password ignored when existingSecret is set
  password: "prod-redis-pass-change-me"
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi
config:
  maxmemory: "512mb"
  maxmemory-policy: "allkeys-lru"
